export const LOGIN_BUTTON_CLICK = "APP/CONATINER/ADMINLOGINPAGE";
export const LOGIN_BUTTON_CLICK_SUCCESS =
    "APP/CONATINER/LOGIN_BUTTON_CLICK_SUCCESS";
export const LOGIN_BUTTON_CLICK_ERROR =
    "APP/CONATINER/LOGIN_BUTTON_CLICK_ERROR";

export const OTP_CHECK = "APP/CONATINER/OTP_CHECK";
export const OTP_CHECK_SUCCESS = "APP/CONATINER/OTP_CHECK_SUCCESS";

export const LOGIN_BUTTON_CLICK_SAGA_CALL = "APP/CONATINER/ADMINLOGINPAGE";

export const MASTER = "APP/CONATINER/MASTER";
