export const FETCH_EXCEL_DATA = "APP/CONATINER/READEXEL/FETCH_EXCEL_DATA";
export const FETCH_EXCEL_DATA_SUCCESS =
    "APP/CONATINER/READEXEL/FETCH_EXCEL_DATA_SUCCESS";
export const FETCH_SHEET_NAME = "APP/CONATINER/READEXEL/FETCH_SHEET_NAME";
export const FETCH_SHEET_NAME_SUCCESS =
    "APP/CONATINER/READEXEL/FETCH_SHEET_NAME_SUCCESS";
export const SEND_EMAIL = "APP/CONATINER/READEXEL/SEND_EMAIL";
export const GET_SHEET_NAME = "APP/CONATINER/READEXEL/GET_SHEET_NAME";
export const ADD_EMAIL_NAME = "APP/CONATINER/READEXEL/ADD_EMAIL_NAME";
