export const FETCH_EXCEL_DATA = "APP/CONATINER/READEXEL/FETCH_EXCEL_DATA";
export const FETCH_EXCEL_DATA_SUCCESS = "APP/CONATINER/READEXEL/FETCH_EXCEL_DATA_SUCCESS";
export const FETCH_SHEET_NAME = "APP/CONATINER/READEXEL/FETCH_SHEET_NAME";
export const FETCH_SHEET_NAME_SUCCESS =
    "APP/CONATINER/READEXEL/FETCH_SHEET_NAME_SUCCESS";
