export const ALLOCATEBATTERY_FORMSUBMIT =
    "RESOURCES/JS/ADMIN/CONTAINERS/ALLOCATEBATTERY/ALLOCATEBATTERY_FORMSUBMIT";

export const GET_PRODUCT_DATA =
    "RESOURCES/JS/ADMIN/CONTAINERS/ALLOCATEBATTERY/GET_PRODUCT_DATA";


export const GET_PRODUCT_DATA_SUCCESS =
"RESOURCES/JS/ADMIN/CONTAINERS/ALLOCATEBATTERY/GET_PRODUCT_DATA_SUCCESS";
