export const GET_GLASS_CATEGROY =
    "RESOURCES/JS/ADMIN/CONTAINERS/ALLOCATEGLASS/GET_GLASS_CATEGROY";
export const GET_GLASS_CATEGROY_SUCCESS =
    "RESOURCES/JS/ADMIN/CONTAINERS/ALLOCATEGLASS/GET_GLASS_CATEGROY_SUCCESS";
